### ISSUE TITLE
代码疑似暴露敏感信息

### ISSUE THREAD

**Issue by glimmeringlight** [shaoyaoqian/issues-anywhere#3]
https://github.com/shaoyaoqian/issues-anywhere/blob/09389e9d8883d8f82e96d063bf2c2b7299d0f7a0/wechat.py#L36-L38

请问一下源码中这里的token和secret重要吗，如果重要的话建议隐藏一下为好，注意信息安全。

**Comment by shaoyaoqian** [comment]
每个都删掉了中间的一长段
